// golemstats-frontend/pages/network/historical.tsx
import { HistoricalComputingChart } from "@/components/charts/HistoricalComputing"
import HistoricalPriceChart from "@/components/charts/HistoricalPrice"
import { HistoricalSpecs } from "@/components/charts/HistoricalSpecs"
import { NetworkVersionAdoption } from "@/components/charts/NetworkVersions"

export default function Home() {
    return (
        <div className="mt-8 grid grid-cols-1 gap-4 lg:grid-cols-12">
            <div className="lg:col-span-12 -mb-4 -mt-4 col-span-12">
                <h1 className="text-2xl font-medium dark:text-gray-300">Historical Statistics</h1>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 col-span-12 gap-4">
                <HistoricalSpecs endpoint="network/historical/stats" title="Providers Online" colors={["#3F51B5"]} yaxisLabel="Providers" />
                <HistoricalSpecs endpoint="network/historical/stats" title="Amount of Cores" colors={["#3F51B5"]} yaxisLabel="Cores" />
                <HistoricalSpecs endpoint="network/historical/stats" title="TB of Memory" colors={["#3F51B5"]} yaxisLabel="Memory" />
                <HistoricalSpecs endpoint="network/historical/stats" title="TB of Disk" colors={["#3F51B5"]} yaxisLabel="Disk" />
            </div>
            <div className="col-span-12 lg:col-span-6 md:col-span-6">
                <HistoricalPriceChart
                    endpoint="network/historical/pricing/median"
                    title="Provider Median Pricing"
                    palette={["#FFED29", "#FF5289", "#00096B"]}
                    allDataPoints={true}
                    annotations={true}
                />
            </div>
            <div className="col-span-12 lg:col-span-6 md:col-span-6">
                <HistoricalPriceChart
                    endpoint="network/historical/pricing/average"
                    title="Provider Average Pricing"
                    palette={["#FFED29", "#FF5289", "#00096B"]}
                    allDataPoints={true}
                    annotations={true}
                />
            </div>
            <div className="col-span-12 ">
                <HistoricalComputingChart
                    endpoint="network/historical/provider/computing"
                    title="Providers computing simultaneously"
                    colors="#0230FF"
                />
            </div>
            <div className="col-span-12">
                <NetworkVersionAdoption />
            </div>
        </div>
    )
}

// src/views/Historical.vue
<!-- This example requires Tailwind CSS v2.0+ -->
<template>
  <div class="max-w-8xl mx-auto sm:px-6 lg:px-8">
    <div class="grid gap-5 grid-cols-12">
      <div class="col-span-12 mt-4 -mb-2">
        <h1 class="text-2xl font-medium dark:text-gray-300">Historical Statistics</h1>
      </div>
      <div class="col-span-12">
        <statsovertime>/</statsovertime>
      </div>
      <div class="col-span-12 lg:col-span-6 md:col-span-6">
        <Pricinghistorical
          :endpoint="'network/historical/pricing/median'"
          :title="'Provider Median Pricing'"
          :palette="['#FFED29', '#FF5289', '#00096B']"
          :allDataPoints="true"
          :annotations="true"
          >/</Pricinghistorical
        >
      </div>
      <div class="col-span-12 lg:col-span-6 md:col-span-6">
        <Pricinghistorical
          :endpoint="'network/historical/pricing/average'"
          :title="'Provider Average Pricing'"
          :palette="['#FFED29', '#FF5289', '#00096B']"
          :allDataPoints="true"
          :annotations="true"
          >/</Pricinghistorical
        >
      </div>
      <div class="col-span-12 lg:col-span-6">
        <Computinghistorical
          :endpoint="'network/historical/provider/computing'"
          :title="'Providers computing simultaneously'"
          :colors="'#0230FF'"
          class="mb-6"
        >
        </Computinghistorical>
      </div>
      <div class="col-span-12 lg:col-span-6 md:col-span-12">
        <newestproviders> </newestproviders>
      </div>
      <div class="col-span-12 lg:col-span-12">
        <Networkversions class="mb-6"> </Networkversions>
      </div>
    </div>
  </div>
</template>

<script>
// @ is an alias to /src
import statsovertime from "@/components/Statsovertime.vue"
import Pricinghistorical from "@/components/Pricinghistorical.vue"
import Computinghistorical from "@/components/Computinghistorical.vue"
import newestproviders from "@/components/newestproviders.vue"
import Networkversions from "@/components/Networkversions.vue"

export default {
  name: "Home",
  components: {
    statsovertime,
    Pricinghistorical,
    Computinghistorical,
    newestproviders,
    Networkversions,
  },
}
</script>
