// src/@core/components/network/networkversions.vue
<template>
  <div>
    <b-col lg="12" md="12">
      <h3>Network Version adoption (24h)</h3>
      <b-card>
        <apexchart
          v-if="loaded"
          width="100%"
          height="250"
          type="area"
          :options="chartOptions"
          :series="series"
        ></apexchart>
        <div class="text-center" v-else>
          <b-spinner variant="primary" label="Text Centered" />
        </div>
      </b-card>
    </b-col>
  </div>
</template>

<script>
import { BCard, BCol, BRow, BSpinner } from 'bootstrap-vue'
import axios from '@axios'
export default {
  components: {
    BCard,
    BRow,
    BCol,
    BSpinner,
  },
  data() {
    return {
      loaded: false,
      series: [],
      chartOptions: {
        chart: {
          id: 'area-datetime',
          type: 'area',
          zoom: {
            autoScaleYaxis: true,
          },
          animations: {
            enabled: false,
            easing: 'linear',
            dynamicAnimation: {
              speed: 1000,
            },
          },
        },
        tooltip: {
          enabled: true,
          x: {
            show: true,
            format: 'HH:mm:ss',
            formatter: undefined,
          },
        },
        dataLabels: {
          enabled: false,
        },
        colors: ['#b5179e', '#560bad', '#3a0ca3', '#72efdd'],
        markers: {
          size: 0,
        },
        stroke: {
          width: 2,
        },
        yaxis: {
          title: {
            text: 'Node count',
            rotate: -90,
            offsetX: 0,
            offsetY: 0,
            style: {
              color: undefined,
              fontSize: '12px',
              fontWeight: 600,
              cssClass: 'apexcharts-yaxis-title',
            },
          },
        },
        xaxis: {
          type: 'datetime',
          title: {
            text: 'Yagna version',
            rotate: -90,
            offsetX: -25,
            offsetY: 10,
            style: {
              color: undefined,
              fontSize: '12px',
              fontWeight: 600,
              cssClass: 'apexcharts-yaxis-title',
            },
          },
          labels: {
            datetimeFormatter: {
              year: 'yyyy',
              month: "MMM 'yy",
              day: 'dd MMM',
              hour: 'HH:mm:ss',
            },
          },
        },
      },
    }
  },
  created() {
    this.utilization()
  },
  mounted: function () {
    this.timer = setInterval(() => {
      this.utilization()
    }, 15000)
  },
  methods: {
    utilization() {
      this.series.length = 0
      axios.get('/v1/network/versions').then((response) => {
        let apiResponse = response.data
        let data = apiResponse.data.result
        data.forEach((obj, index) => {
          let values = obj['values']
          let computing = []
          for (var i in values) {
            var time = values[i][0] * 1000
            computing.push([time, values[i][1]])
          }
          this.series.push({
            data: computing,
            name: obj['metric']['version'].slice(-3, 5),
          })
        })
      })
      this.loaded = true
      console.log('ned')
    },
  },
}
</script>

// golemstats-frontend/components/charts/NetworkVersions.tsx
import { fetcher } from "@/fetcher"

import React, { useEffect, useState } from "react"
import { ApexOptions } from "apexcharts"
import dynamic from "next/dynamic"
import useSWR from "swr"

const ApexChart = dynamic(() => import("react-apexcharts"), { ssr: false })

export const NetworkVersionAdoption: React.FC = () => {
    const [loaded, setLoaded] = useState<boolean>(false)
    const [series, setSeries] = useState<{ data: any[]; name: string }[]>([
        {
            data: [],
            name: "Providers",
        },
    ])

    const { data, error } = useSWR("network/versions", fetcher)

    const chartOptions: ApexOptions = {
        chart: {
            type: "bar",
            height: 350,
        },
        plotOptions: {
            bar: {
                borderRadius: 4,
                horizontal: false,
            },
        },
        yaxis: {
            title: {
                text: "Providers",
                rotate: -90,
                offsetX: 0,
                offsetY: 0,
                style: {
                    fontSize: "12px",
                    fontWeight: 600,
                    cssClass: "apexcharts-yaxis-title",
                },
            },
        },
        xaxis: {
            title: {
                text: "Yagna Version",
                offsetX: 0,
                offsetY: 0,
                style: {
                    fontSize: "12px",
                    fontWeight: 600,
                    cssClass: "apexcharts-yaxis-title",
                },
            },
        },
        colors: ["#0000ff"],
        dataLabels: {
            enabled: false,
        },
    }

    useEffect(() => {
        if (data) {
            data.forEach((obj: any, index: number) => {
                const versions = obj["version"]
                const count = obj["count"]

                series[0].data.push({ x: versions, y: count })
            })
            setLoaded(true)
        }
    }, [data])

    return (
        <div className="bg-white dark:bg-gray-800 pt-5 px-4 sm:px-6 shadow rounded-lg overflow-hidden">
            <div className="relative">
                <div className="absolute top-0 right-0 -mr-1 -mt-1 w-4 h-4 rounded-full bg-green-300 animate-ping"></div>
                <div className="absolute top-0 right-0 -mr-1 -mt-1 w-4 h-4 rounded-full bg-green-300"></div>
                <h1 className="text-2xl mb-2 font-medium dark:text-gray-300">Network Version Adoption</h1>

                {loaded && <ApexChart width="100%" height={350} type="bar" options={chartOptions} series={series} />}
            </div>
        </div>
    )
}
